# Site settings
title: American Literature
email: bionicle.dragon@gmail.com
description: "This site lets me take notes for my 11th grade English class."
baseurl: ""
url: "http://porglezomp.github.io/am-lit"
twitter_username: porglezomp
github_username:  porglezomp

# Build settings
markdown: kramdown
permalink: pretty
