# Site settings
title: American Literature
email: bionicle.dragon@gmail.com
description: "This site lets me take notes for my 11th grade English class."
baseurl: "/am-lit"
url: "http://localhost:4000"
twitter_username: porglezomp
github_username:  porglezomp

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Build settings
markdown: kramdown
permalink: pretty
